alias sudo='sudo '
alias ll='ls -la --color'
alias la='ls -a --color'
alias v='nvim'
alias vi='nvim'
alias vim='nvim'
alias grep='grep --color=auto'

alias stowi='stow --ignore="README.md" */'
alias stowai='stow --adopt --ignore="README.md" */'
alias stowupdate='git pull && stow --adopt --ignore="README.md" */ && git restore .'
